In [1]:
import math
import numpy as np
import pandas as pd

# Reading the csv and Basic stuff

In [2]:
df = pd.read_excel("cancer patient data sets.xlsx")

df

Patient Id  Age  Gender  Air Pollution  Alcohol use  Dust Allergy  \
0           P1   33       1            2.0          NaN           5.0   
1          P10   17       1            3.0          1.0           5.0   
2         P100   35       1            4.0          5.0           6.0   
3        P1000   37       1            7.0          7.0           7.0   
4         P101   46       1            6.0          8.0           NaN   
..         ...  ...     ...            ...          ...           ...   
995       P995   44       1            6.0          7.0           7.0   
996       P996   37       2            6.0          8.0           7.0   
997       P997   25       2            4.0          5.0           6.0   
998       P998   18       2            6.0          8.0           7.0   
999       P999   47       1            6.0          5.0           6.0   

     OccuPational Hazards  Genetic Risk  chronic Lung Disease  Balanced Diet  \
0                     4.0             3                     2              2   
1                     3.0             4                     2              2   
2                     5.0             5                     4              6   
3                     7.0             6                     7              7   
4                     7.0             7                     6              7   
..                    ...           ...                   ...            ...   
995                   7.0             7                     6              7   
996                   7.0             7                     6              7   
997                   5.0             5                     4              6   
998                   7.0             7                     6              7   
999                   5.0             5                     4              6   

     ...  Fatigue  Weight Loss  Shortness of Breath  Wheezing  \
0    ...        3            4                    2         2   
1    ...        1            3                    7         8   
2    ...        8            7                    9         2   
3    ...        4            2                    3         1   
4    ...        3            2                    4         1   
..   ...      ...          ...                  ...       ...   
995  ...        5            3                    2         7   
996  ...        9            6                    5         7   
997  ...        8            7                    9         2   
998  ...        3            2                    4         1   
999  ...        8            7                    9         2   

     Swallowing Difficulty  Clubbing of Finger Nails  Frequent Cold  \
0                        3                         1              2   
1                        6                         2              1   
2                        1                         4              6   
3                        4                         5              6   
4                        4                         2              4   
..                     ...                       ...            ...   
995                      8                         2              4   
996                      2                         4              3   
997                      1                         4              6   
998                      4                         2              4   
999                      1                         4              6   

     Dry Cough  Snoring   Level  
0            3        4     Low  
1            7        2  Medium  
2            7        2    High  
3            7        5    High  
4            2        3    High  
..         ...      ...     ...  
995          5        3    High  
996          1        4    High  
997          7        2    High  
998          2        3    High  
999          7        2    High  

[1000 rows x 25 columns]

## Getting unique values

In [3]:
df['Alcohol use'].unique()

array([nan,  1.,  5.,  7.,  8.,  4.,  3.,  6.,  2.])

In [4]:
df['Age'].unique()

array([33, 17, 35, 37, 46, 52, 28, 44, 64, 39, 34, 27, 73, 36, 14, 24, 53,
       62, 29, 65, 38, 19, 42, 32, 25, 45, 26, 48, 22, 18, 23, 47, 61, 55,
       31, 49, 43, 51, 54, 63], dtype=int64)

In [6]:
df['Dust Allergy'].unique()

array([ 5.,  6.,  7., nan,  4.,  2.,  8.,  1.,  3.])

In [7]:
df['OccuPational Hazards'].unique()

array([ 4.,  3.,  5.,  7., nan,  2.,  6.,  8.,  1.])

## Describing the dataset

In [8]:
df.describe()

Age       Gender  Air Pollution  Alcohol use  Dust Allergy  \
count  1000.000000  1000.000000     998.000000   998.000000    998.000000   
mean     37.174000     1.402000       3.840681     4.560120      5.164329   
std      12.005493     0.490547       2.032255     2.620782      1.981623   
min      14.000000     1.000000       1.000000     1.000000      1.000000   
25%      27.750000     1.000000       2.000000     2.000000      4.000000   
50%      36.000000     1.000000       3.000000     5.000000      6.000000   
75%      45.000000     2.000000       6.000000     7.000000      7.000000   
max      73.000000     2.000000       8.000000     8.000000      8.000000   

       OccuPational Hazards  Genetic Risk  chronic Lung Disease  \
count            999.000000   1000.000000           1000.000000   
mean               4.839840      4.580000              4.380000   
std                2.108855      2.126999              1.848518   
min                1.000000      1.000000              1.000000   
25%                3.000000      2.000000              3.000000   
50%                5.000000      5.000000              4.000000   
75%                7.000000      7.000000              6.000000   
max                8.000000      7.000000              7.000000   

       Balanced Diet      Obesity  ...  Coughing of Blood      Fatigue  \
count    1000.000000  1000.000000  ...        1000.000000  1000.000000   
mean        4.491000     4.465000  ...           4.859000     3.856000   
std         2.135528     2.124921  ...           2.427965     2.244616   
min         1.000000     1.000000  ...           1.000000     1.000000   
25%         2.000000     3.000000  ...           3.000000     2.000000   
50%         4.000000     4.000000  ...           4.000000     3.000000   
75%         7.000000     7.000000  ...           7.000000     5.000000   
max         7.000000     7.000000  ...           9.000000     9.000000   

       Weight Loss  Shortness of Breath     Wheezing  Swallowing Difficulty  \
count  1000.000000          1000.000000  1000.000000            1000.000000   
mean      3.855000             4.240000     3.777000               3.746000   
std       2.206546             2.285087     2.041921               2.270383   
min       1.000000             1.000000     1.000000               1.000000   
25%       2.000000             2.000000     2.000000               2.000000   
50%       3.000000             4.000000     4.000000               4.000000   
75%       6.000000             6.000000     5.000000               5.000000   
max       8.000000             9.000000     8.000000               8.000000   

       Clubbing of Finger Nails  Frequent Cold    Dry Cough      Snoring  
count               1000.000000    1000.000000  1000.000000  1000.000000  
mean                   3.923000       3.536000     3.853000     2.926000  
std                    2.388048       1.832502     2.039007     1.474686  
min                    1.000000       1.000000     1.000000     1.000000  
25%                    2.000000       2.000000     2.000000     2.000000  
50%                    4.000000       3.000000     4.000000     3.000000  
75%                    5.000000       5.000000     6.000000     4.000000  
max                    9.000000       7.000000     7.000000     7.000000  

[8 rows x 23 columns]

# Format of each values

In [10]:
df.dtypes

Patient Id                   object
Age                           int64
Gender                        int64
Air Pollution               float64
Alcohol use                 float64
Dust Allergy                float64
OccuPational Hazards        float64
Genetic Risk                  int64
chronic Lung Disease          int64
Balanced Diet                 int64
Obesity                       int64
Smoking                       int64
Passive Smoker                int64
Chest Pain                    int64
Coughing of Blood             int64
Fatigue                       int64
Weight Loss                   int64
Shortness of Breath           int64
Wheezing                      int64
Swallowing Difficulty         int64
Clubbing of Finger Nails      int64
Frequent Cold                 int64
Dry Cough                     int64
Snoring                       int64
Level                        object
dtype: object

## Changing the dtypes

In [13]:
df['Chest Pain'].astype("float")

df['Frequent Cold'].astype("float")

df['Air Pollution'].astype("float")

df.dtypes

Patient Id                   object
Age                           int64
Gender                        int64
Air Pollution               float64
Alcohol use                 float64
Dust Allergy                float64
OccuPational Hazards        float64
Genetic Risk                  int64
chronic Lung Disease          int64
Balanced Diet                 int64
Obesity                       int64
Smoking                       int64
Passive Smoker                int64
Chest Pain                    int64
Coughing of Blood             int64
Fatigue                       int64
Weight Loss                   int64
Shortness of Breath           int64
Wheezing                      int64
Swallowing Difficulty         int64
Clubbing of Finger Nails      int64
Frequent Cold                 int64
Dry Cough                     int64
Snoring                       int64
Level                        object
dtype: object

## Filling Na values

In [5]:
AlcoholUseMedian = df['Chest Pain'].median()

DustAllergyMedian = df['Dust Allergy'].median()

AirPollutionMedian = df['Air Pollution'].median() 

In [7]:
df['Air Pollution'] = df['Air Pollution'].fillna(AirPollutionMedian)

df['Alcohol use'] = df['Alcohol use'].fillna(AlcoholUseMedian)

df['Dust Allergy'] = df['Dust Allergy'].fillna(DustAllergyMedian)

df.head(10)

Patient Id  Age  Gender  Air Pollution  Alcohol use  Dust Allergy  \
0         P1   33       1            2.0          4.0           5.0   
1        P10   17       1            3.0          1.0           5.0   
2       P100   35       1            4.0          5.0           6.0   
3      P1000   37       1            7.0          7.0           7.0   
4       P101   46       1            6.0          8.0           6.0   
5       P102   35       1            4.0          5.0           6.0   
6       P103   52       2            2.0          4.0           5.0   
7       P104   28       2            3.0          1.0           4.0   
8       P105   35       2            4.0          5.0           6.0   
9       P106   46       1            2.0          3.0           4.0   

   OccuPational Hazards  Genetic Risk  chronic Lung Disease  Balanced Diet  \
0                   4.0             3                     2              2   
1                   3.0             4                     2              2   
2                   5.0             5                     4              6   
3                   7.0             6                     7              7   
4                   7.0             7                     6              7   
5                   5.0             5                     4              6   
6                   4.0             3                     2              2   
7                   3.0             2                     3              4   
8                   NaN             6                     5              5   
9                   2.0             4                     3              3   

   ...  Fatigue  Weight Loss  Shortness of Breath  Wheezing  \
0  ...        3            4                    2         2   
1  ...        1            3                    7         8   
2  ...        8            7                    9         2   
3  ...        4            2                    3         1   
4  ...        3            2                    4         1   
5  ...        8            7                    9         2   
6  ...        3            4                    2         2   
7  ...        3            2                    2         4   
8  ...        1            4                    3         2   
9  ...        1            2                    4         6   

   Swallowing Difficulty  Clubbing of Finger Nails  Frequent Cold  Dry Cough  \
0                      3                         1              2          3   
1                      6                         2              1          7   
2                      1                         4              6          7   
3                      4                         5              6          7   
4                      4                         2              4          2   
5                      1                         4              6          7   
6                      3                         1              2          3   
7                      2                         2              3          4   
8                      4                         6              2          4   
9                      5                         4              2          1   

   Snoring   Level  
0        4     Low  
1        2  Medium  
2        2    High  
3        5    High  
4        3    High  
5        2    High  
6        4     Low  
7        3     Low  
8        1  Medium  
9        5  Medium  

[10 rows x 25 columns]